-- Drop all tables in reverse dependency order
DROP TABLE IF EXISTS cousins CASCADE;
DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS credit_card_data CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS banks CASCADE;
DROP TABLE IF EXISTS users CASCADE;
