ALTER TABLE transactions ADD COLUMN considered BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE transactions ADD COLUMN is_open_finance BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE transactions ADD COLUMN tags TEXT[];
ALTER TABLE transactions ADD COLUMN payment_method VARCHAR(255);
ALTER TABLE transactions ADD COLUMN manipulated BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE transactions ADD COLUMN cousin INT NOT NULL DEFAULT 0;