ALTER TABLE accounts ADD COLUMN initial_balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00;
ALTER TABLE accounts ADD COLUMN is_open_finance_account BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE accounts ADD COLUMN closed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE accounts ADD COLUMN "order" INT NOT NULL DEFAULT 90;
ALTER TABLE accounts ADD COLUMN description TEXT;
ALTER TABLE accounts ADD COLUMN removed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE accounts ADD COLUMN hidden_by_user BOOLEAN NOT NULL DEFAULT FALSE;  